---
title: "First Knit"
author: melishawright
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended Compton Senior High and graduated in 2008. I have always done better in math rather than English,I love math I have never been a good writer in my opinion.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer 
I currently have a Mac Book Air, I rate myself on a scale of 1-10 for computer literacy a 6. I know how to do the basic fundamentals but I am far from an expert. I have a pretty good internet connection at home, very reliable.
  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called Melisha by all.    
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to achieve in life is simply achievement itself in all areas of my life. I want to have balance and harmony in everything I do. I am looking forward to   taking Anatomy and Physiology, I cannot wait to learn about the human body and how it works. I am trying to achieve my Associates in Nursing.    
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have never been out of the country but I hope to go to Israel this year. I have never been in the military but if I were to be drafted I would definitely want to be in the Reserves and work on the medical side of things. Definitely not on the front line!   
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I did not take neither Math 115 or 116, I need an "A" in this class to satisfy a requirement for the nursing program. I plan to take advantage of office hours and volunteer to share my screen as much as possible to help me retain information and help me get more comfortable with the different systems.    
   
 






  




